### ISSUE TITLE
unhandled exception

### ISSUE THREAD

**Issue by scotscottmca** [PatchMyPCTeam/WSUS-Clippy#2]
```
Application: MEM Patching Optimizer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: http://System.Net.WebException
   at Microsoft.UpdateServices.Administration.AdminProxy.CreateUpdateServer(System.Object[])
   at MEMPatchingOptimizer.ViewModel.ViewModel..ctor()
   at MEMPatchingOptimizer.MainWindow..ctor()

Exception Info: http://System.Windows.Markup.XamlParseException
   at http://System.Windows.Markup.XamlReader.RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)
   at http://System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at http://System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at http://System.Windows.Markup.XamlReader.LoadBaml(http://System.IO.Stream, http://System.Windows.Markup.ParserContext, System.Object, Boolean)
   at http://System.Windows.Application.LoadBamlStreamWithSyncInfo(http://System.IO.Stream, http://System.Windows.Markup.ParserContext)
   at http://System.Windows.Application.DoStartup()
   at http://System.Windows.Application.<.ctor>b__1_0(System.Object)
   at http://System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at http://System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at http://System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at http://System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at http://System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at http://MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at http://System.Windows.Threading.DispatcherOperation.Invoke()
   at http://System.Windows.Threading.Dispatcher.ProcessQueue()
   at http://System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at http://System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at http://System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at http://System.Windows.Threading.Dispatcher.LegacyInvokeImpl(http://System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(http://System.Windows.Interop.MSG ByRef)
   at http://System.Windows.Threading.Dispatcher.PushFrameImpl(https://t.co/EhQj9yQlar.Threading.DispatcherFrame)
   at http://System.Windows.Application.RunDispatcher(System.Object)
   at http://System.Windows.Application.RunInternal(https://t.co/EhQj9yQlar.Window)
   at http://MEMPatchingOptimizer.App.Main()
```

**Comment by scotscottmca** [comment]
Still unable to reproduce this issue in a lab environment
